# Example setup scripts for training.

name: train-1-small
description: Train and test with just NMM (DFT ion) - small parameters
task: iam2structure
model: cnn+rnn

learning-rate: 0.001
batch-size: 128
epochs: 1
logging-period: 40
checkpoints: ../checkpoints

vocab-size: 20
embedding-size: 64

network:
  kernel-size: 5
  cnn-size: 32
  cnn-num-layers: 1
  rnn-size: 32
  hidden-size: 64

data:
  - mat: ../data/NMM_iondft_IAM_pattern.mat
    bonds: ../data/NMM.bonds
    train: 10000-159999
    test: 1-9999,170000-173977,0
