# Example setup scripts for training.

name: train-2
description: Transformer (just NMM (DFT ion))
task: iam2structure
model: transformer

learning-rate: 0.001
batch-size: 128
epochs: 10
logging-period: 10
checkpoints: ../checkpoints

vocab-size: 20
embedding-size: 512

network:
  kernel-size: 5
  cnn-size: 256
  cnn-num-layers: 2
  rnn-size: 512
  hidden-size: 512

data:
  - mat: ../data/NMM_iondft_IAM_pattern.mat
    bonds: ../data/NMM.bonds
    train: 0-159999
    test: 160000-173977
