# Example setup scripts for training.

name: train-3
description: Transformer (with NMM DFT-ion coherent patterns)
task: iam2structure
model: transformer

learning-rate: 0.001
batch-size: 128
# epochs: 10
epochs: 1
logging-period: 10
checkpoints: ../checkpoints

vocab-size: 20
embedding-size: 512
max-threads: 14

network:
  num-encoders: 2
  num-decoders: 2
  window-size: 18

data:
  - mat: ../data/NMM_iondft_IAM_coherent_pattern.mat
    data-key: I_IAM_coherent_patterns
    bonds: ../data/NMM.bonds
    train: 0-159999
    test: 160000-173996
