# Example setup scripts for training.

name: train-transformer-dt-norm
description: 
task: iam2structure
model: transformer

learning-rate: 0.001
batch-size: 128
# epochs: 10
epochs: 1
logging-period: 10
checkpoints: ../checkpoints

vocab-size: 20
embedding-size: 128
max-threads: 14

network:
  num-encoders: 2
  num-decoders: 2
  window-size: 14

data:
  - mat: ../data/Norm_Stand_DT_IAM_coherent_patterns.mat
    data-key: norm_pattern
    bonds: ../data/DT.bonds
    train: 0-159999
    test: 160000-173996
