# Example setup scripts for training.

name: train-cnn-dt-coherent
description: 
task: iam2structure
model: cnn

learning-rate: 0.005
batch-size: 128
# epochs: 10
epochs: 3
logging-period: 10
checkpoints: ../checkpoints

vocab-size: 20
embedding-size: 128
max-threads: 14

network:
  cnns:
    - [32, 5]
    - [32, 3]
    - [32, 3]
  denses:
    - 256
    - 128
    - 64
  num-atoms: 14

data:
  - mat: ../data/DT_IAM_coherent_pattern.mat
    data-key: I_IAM_coherent_patterns
    bonds: ../data/DT.bonds
    train: 0-159999
    test: 160000-173996
